#分割线为属性值 springboot2.4+ new
config:
  api : "api"
---
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id : user-service-route # id
          uri : lb://user-service # lb
          predicates:
            - Path=/${config.api}/user/**
          filters:
            - StripPrefix=1

        - id : post-service
          uri : lb://post-service
          predicates:
            - Path=/${config.api}/user/**
          filters:
            - StripPrefix=1

        - id : test-service-route
          uri : lb://test-service
          predicates:
            - Path=/${config.api}/test/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka