server:
  port: 8090

spring:
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      connect-timeout: 300ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_system?&serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&userSSL=false&autoReconnect=true
    username: root
    password: 896093827y
  application:
    name: post-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case : false


